image: 'docker:latest'

services:
    - docker:dind

cache:
    paths:
        - /app/node_modules/

stages:
    - build

build:
    stage: build
    script:
        - docker build . -t crowfx/training-ci-cd
