sudo: required

services:
    - docker

language: generic

before_install:
    - docker build -f Dockerfile.dev -t react-frontend .

script:
    - docker run react-frontend npm run test -- --watchAll=false
